project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "img/"

website:
  title: "Bayes, *stat*!"

  navbar:
    background: primary
    left:
      - file: index.qmd
        text: "Home"
      - file: day1.qmd
        text: "Day 1" 
      - file: day2.qmd
        text: "Day 2"
      - file: resources.qmd
        text: "Resources"

  sidebar:
    - title: "Day 1"
      style: "docked"
      contents:
        - file: day1.qmd
          text: "Learning objectives"
        - day1-1.qmd
        - day1-2.qmd
        - day1-recap.qmd
    - title: "Day 2"
      style: "docked"
      contents:
        - file: day2.qmd
          text: "Learning objectives"
        - day2-1.qmd
        - day2-2.qmd
        - day2-recap.qmd

  page-navigation: true


format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

callout-icon: false

