project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources:
    - "img/"
    - "data/"

website:
  title: "Bayes, *stat*!"

  navbar:
    background: primary
    left:
      - file: index.qmd
        text: "Home"
      - file: day1/learningobj.qmd
        text: "Day 1" 
      - file: day2/learningobj.qmd
        text: "Day 2"
      - file: resources.qmd
        text: "Resources"


  sidebar:
    - title: "Day 1"
      style: "docked"
      contents:
        - file: day1/learningobj.qmd
          text: "Learning objectives"
        - day1/example.qmd
        - day1/probable-probs.qmd
        - day1/unif-prior.qmd
        - day1/informative-prior.qmd
        - file: day1/dancing-pstrs.qmd
          text: "Dancing posteriors"
        - file: day1/interim-summary.qmd
          text: "Interim summary"
        - day1/posteriors.qmd
        - day1/cri.qmd
        - day1/mcmc.qmd
        - day1/generative-models.qmd
        - day1/day1-recap.qmd
    - title: "Day 2"
      style: "docked"
      contents:
        - file: day2/learningobj.qmd
          text: "Learning objectives"
        - day2/setup.qmd
        - day2/build-model.qmd
        - day2/fit-model.qmd
        - day2/report-model.qmd
        - day2/day2-recap.qmd

  page-navigation: true


format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true

callout-icon: false

