---
title: "Day 2 Recap"
---

**What is the workflow for running a Bayesian analysis?**

- Find a suitable likelihood.
- Identify the parameters in the model.
- Find appropriate priors (using, e.g., prior predictive checks).
- Fit the model.
- Check convergence.
- Compare posterior predictive distributions to the true data.
- If the model is off: Tweak it and begin again. Else: Report!


**How do we fit a Bayesian model using brms?**

- Actually much like we would with lme4-based analyses!
- And with a little more patience.


**How do we check that it's a good model?**

- To check convergence, we use diagnostics like trace plots (🐛) and Rhat values.
- To see whether the model adequately captures the generative process behind the data, we compare data that the model generates to the true data we observed using posterior predictive checks.


**How would we report the results in a publication?**

- Parameter estimates can be reported similarly to how you would report a frequentist model, bearing in mind that we are not rejecting any nulls, nor are we finding evidence for any effects.


